Upload cards as attachment and cleanup cards.js
bra1n/judgebot pull request #15
Opened 2016-11-01 19:23 UTC by hgarus

Fixes #4 .

Not quite sure where to put `longestCommonPrefix`. Definitely doesn't belong on the class, feels like it should be in it's own module, but I'm not sure if we want relative paths all over the place (such as `require("../../helpers/stringhelper")`. An alternative would be using common-prefix from npm.

I have replaced the use of a map to find cards with card images with a slightly different approach using lodash, personally I find it more readable, if you think differently feel free to let me know.

I have tested this by running a selfbot and there is a noticable delay on answer times due to the image upload. I'm not sure if the added cleanliness is actually worth the delay, compared to just adding the cardImage URL to the message.

2016-11-02 09:33 UTC, hcschild requested changes
This looks goods except for some minor issues. Additionally you need to update your package.json

2016-11-02 09:33 UTC, hcschild commented on aggregators/mtg_cards/cards.js
> +            card = _.maxBy(uniqCards, c => longestCommonPrefix(cardName, c.name.toLowerCase()));
Is this better then just `uniqCards.find(c => c.name.toLowerCase().startsWith(cardName));`?

2016-11-02 09:33 UTC, hcschild commented on aggregators/mtg_cards/cards.js
> +                    response += "\n\nOther matching cards: " + otherCardNames.join(", ");
It would be better to `join` the card names with `join(" | ")` because some card names contain commas.

2016-11-02 09:33 UTC, hcschild commented on aggregators/mtg_cards/cards.js
> +function longestCommonPrefix(...strings) {
As I said in my comment for line `39` I don't know if this is needed.

2016-11-02 10:02 UTC, bra1n commented on aggregators/mtg_cards/cards.js
> +                    response += "\n\nOther matching cards: " + otherCardNames.join(", ");
I'd also put `*` around the card names.

2016-11-02 11:05 UTC, hgarus commented on aggregators/mtg_cards/cards.js
> +            card = _.maxBy(uniqCards, c => longestCommonPrefix(cardName, c.name.toLowerCase()));
Maybe I've been overthinking this. You're right that there probably aren't any search results where we only have a partial match on the prefix and still want to prefer that result.

2016-11-02 22:23 UTC, bra1n commented on aggregators/mtg_cards/cards.js
> +function longestCommonPrefix(...strings) {
Probably not needed, or if it really was, then not as an external function. ;)

2016-11-03 09:06 UTC, bra1n commented
Looks good to me now.

2016-11-03 09:06 UTC, bra1n approved these changes

2016-11-03 09:06 UTC, merged