Various /cr bug fixes
bra1n/judgebot pull request #180
Opened 2022-09-16 08:25 UTC by lunakv

This PR addresses several issues in the `/cr` slash command code.

- The rules reference to Yawgatog was linked with plain HTTP, even though the site uses HTTPS. This has been rectified.
- The `SlashChoice` import was unused and thus removed.
- The logic for converting rules into element IDs was incomplete. After consulting with Yawgatog's maintainer, a new method was added that produces fully correct transformations for these links.
- The command was case-sensitive. For example, `/cr Unearth` would return no results, even though `/cr unearth` would lead to the correct glossary entry (titled "Unearth"). The search term is now explicitly lowercased to make the search case-insensitive.
- Due to the fuzzy nature of glossary searching, sometimes the actual title of an entry would be different than the search that matched it. Because of this, the contents of `rule` itself aren't necessarily sufficient to produce a valid link to that glossary entry. *(For example, `/cr partner` would create a link to `#partner`, but the correct link would be to the full `#partner_partner_with_name`)*. This has been addressed by the glossary dict now storing not only the definitions themselves, but also the actual value of the term the search is referring to.

2022-09-16 08:43 UTC, multimeric commented
Sounds great!

2022-09-16 09:02 UTC, multimeric requested changes
Since you probably have a few examples in your head about how the yawgatog URL parsing works, could you write a few simple tests for the `ruleToUrlSegment` function please? You can use https://github.com/bra1n/judgebot/blob/develop/test/rules/mtr.ts as a template.

2022-09-16 09:02 UTC, multimeric commented on modules/cr.ts
> +class GlossaryEntry {
I think it would make more sense for this to be an `interface` rather than a class here, since we don't have any methods etc.

2022-09-16 09:02 UTC, multimeric commented on modules/cr.ts
> +      .replace(/[^a-z0-9-]/g, "_") // anything besides alphanum chars and hyphens becomes underscores
Isn't this going to strip out upper case characters?

2022-09-16 09:05 UTC, lunakv commented on modules/cr.ts
> +      .replace(/[^a-z0-9-]/g, "_") // anything besides alphanum chars and hyphens becomes underscores
Any argument passed into this is already fully lowercase.

2022-09-16 09:10 UTC, lunakv commented
To be clear, the method isn't based on found examples, it's a direct recreation of how I've been told the Yawgatog algorithm works by its maintainer. That said, if you think it's necessary I can probably whip up a few examples.

2022-09-16 09:12 UTC, lunakv commented on modules/cr.ts
> +class GlossaryEntry {
Agreed. I actually tried an interface first, but ran into some issues with the discord API that were seemingly fixed by converting to a class. But now that I tried turning it back into an interface, those issues no longer appear, so they were probably unrelated.

2022-09-18 14:42 UTC, lunakv commented on modules/cr.ts
> +      .replace(/[^a-z0-9-]/g, "_") // anything besides alphanum chars and hyphens becomes underscores
After some more thought, I decided that while that is true (at least for now), it's a bit too opaque, and the small optimization isn't worth the lack of clarity, so I made the method case-insensitive anyway.

2022-09-18 14:43 UTC, lunakv commented
I added some sample tests for the `ruleToUrl` method (and refactored it a smidge).

2022-09-18 15:33 UTC, multimeric commented
Looks good. However I'm realising that I never properly configured the tests, so I'm going through the nightmare that is configuring jest + ts + esm right now. If you were able to get it working, let me know.

2022-09-18 15:42 UTC, lunakv commented
I actually fixed one issue with the tests in this PR, namely that they couldn't import the classes they were testing with ts set to "CommonJS" module. Some other hurdles that I went through to get things working:
- this repo uses mocha, not jest
- the tests import the built js files, not the ts source, so you need to build the project before running them (I think)
- you need to have the DISCORD_TOKEN env var set even when running tests.

With those, running `mocha` on this branch seems to at least run the tests correctly, and the CR tests complete successfully. A bunch of the MTR tests still fail, though I haven't really looked into why.

2022-09-28 10:50 UTC, lunakv commented
Unless you feel like this is a blocker, I'd suggest merging this and filing a separate issue for fixing the tests.

2022-09-28 14:53 UTC, multimeric approved these changes

2022-09-28 14:53 UTC, merged